### ISSUE TITLE
Need support for the changed API handling of New Teams

### ISSUE THREAD

**Issue by Dowser** [L-C-P/TouchPortalTeamsPlugin#2]
Since the New Teams don't rely on any API tokens any more but a consent request the connection needs to be updated.

**Comment by L-C-P** [comment]
Interesting! Do you have any information? Api documentation or an equal resource? I'm still using the old Teams, because Teams is missing the privacy setting for the token.

**Comment by L-C-P** [comment]
Ok. I found the new api docu. I will implement the changes shortly.

**Comment by L-C-P** [comment]
It's nearly done. Testing it today. It was a little bit complicated, as long as my Teams 2.1 on Mac is not supporting the 3rd Part API.

**Comment by haris2887** [comment]
I am still using the Teams Classic for Mac. The new teams seems to be missing the API completely. There is a lot of discussion on the MS forums about this. 
I don't mind staying on the older teams classic though.

**Comment by haris2887** [comment]
I have also noticed that the API for mute function works perfectly.
However the other apis such as Webcam on.off or Blur background, although it works it does not detect the state of the changes.

**Comment by L-C-P** [comment]
> I have also noticed that the API for mute function works perfectly. However the other apis such as Webcam on.off or Blur background, although it works it does not detect the state of the changes.

That is interesting. It is working for me. Maybe it is fixed with V2 of the Plugin. Teams classic is also supporting the new API (see readme).

**Comment by L-C-P** [comment]
New PlugIn V2 for the API/Teams 2 is here. I tested it only with Teams classic on Mac. Because the new Teams is missing the 3rd party api integration on Mac. But Teams classic is also supporting the new API. So hopefully it will work also with Teams 2.x.
Please test and report. If everything works as expected, I can change the prerelease state to stable.

**Comment by PhantasmNZ** [comment]
Seems to work great Denis - I'll report back if I find anything - I basically use this plugin all day every day as I pretty much live in Teams - Thank you so much for your hard work and support on this plugin - TouchPortal is my absolutely indispensable tool to manage my daily work life - and your plugin brings everything together making it easy to get things done - thanks again!!!!

**Comment by haris2887** [comment]
I have tested this also, Works great. 
You can close this issue now in Github :)

**Comment by L-C-P** [comment]
> Seems to work great Denis - I'll report back if I find anything - I basically use this plugin all day every day as I pretty much live in Teams - Thank you so much for your hard work and support on this plugin - TouchPortal is my absolutely indispensable tool to manage my daily work life - and your plugin brings everything together making it easy to get things done - thanks again!!!!

Thank you very much for your kind words.

Btw. The new Teams on the Mac now also supports API 2.
