### ISSUE TITLE
Is Teams Connected State status working for anyone in API v2?

### ISSUE THREAD

**Issue by gm1168** [L-C-P/TouchPortalTeamsPlugin#5]
I upgraded to API v2 to support new Teams and found one potential issue.

All my existing actions and states in TouchPortal seem to work fine with new Teams, except for the Connected State (Teams is running).
This status used to work in Touch Portal, but now only shows the disconnected state.
I created a new button in TouchPortal for state and it shows the same behavior as the existing one I had.

Everything else appears to work fine (actions and status:  Recording is On/Off, Camera is on/off, Raise Hand, Mute, etc...)

Just the connected state has an issue.  Has anyone had success with TouchPortal showing the correct status of the new Teams app when using API v2?

**Comment by L-C-P** [comment]
Hi,
can you please test v2.0.1. It should fix the problem.

**Comment by gm1168** [comment]
Just installed 2.0.1 and the Connected State status works now for both my "new" and existing buttons.
Thank you!
