### ISSUE TITLE
Unread message Event

### ISSUE THREAD

**Issue by CrazyShini** [L-C-P/TouchPortalTeamsPlugin#7]
Hi, I've been tried the APP and it's "Unread message" event. Seems like only works if you're in a call, but doesn't work if as a "normal use" (or not in a call).

Don't know if it's possible, but,... there is any possibility to get the information of "Unread messages" event from any chat, even if you are not in a call? Or all the events and actions are programmed only for a call/streams, and there are no possibility to work without a call?

Thanks for all the effort with this app.

**Comment by L-C-P** [comment]
Hi,

I'm sorry, but that is not possible. I just "forwarding" the events from teams. As long as teams is only providing this events during an active call, there is no information I can use.
